trigger:
  batch: true
  branches:
    include:
    - main
    - 'v1.*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
    - .github/
    - azure-pipelines/release.yml

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  ci_feed: https://pkgs.dev.azure.com/hymccord/_packaging/CI/nuget/v3/index.json # Azure Artifacts feed URL
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages/

jobs:
- template: azure-pipelines/build.yml