steps:
  - task: DotNetCoreCLI@2
    displayName: 🛠 dotnet pack
    inputs:
      command: pack
      packagesToPack: 'src/**/*.csproj'
      packDirectory: '$(Build.ArtifactsStagingDirectory)/packages'

  - publish: $(Build.ArtifactsStagingDirectory)/packages
    artifact: packages
    displayName: 📢 Publish artifacts